name = "kredopay-web-app"
compatibility_date = "2024-12-31"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Cloudflare Pages configuration
[env.production]
compatibility_date = "2024-12-31"
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_date = "2024-12-31"
compatibility_flags = ["nodejs_compat"]
